### ISSUE TITLE
PolyUtil.encode is not a function at client.direction error

### ISSUE THREAD

**Issue by oidele** [BunHouth/geometry-library#1]
Hi,

I am not able to get this module to work with NodeJS deployed to Firebase cloud as a cloud function. I keep getting the TypeError message "PolyUntil is not a function at client.directions". I get this error even when I try to execute the examples you provided.
Is this module supported with server-side NodeJS hosted on Firebase as a cloud function?

**Comment by BunHouth** [comment]
> Hi,
> 
> I am not able to get this module to work with NodeJS deployed to Firebase cloud as a cloud function. I keep getting the TypeError message "PolyUntil is not a function at client.directions". I get this error even when I try to execute the examples you provided.
> Is this module supported with server-side NodeJS hosted on Firebase as a cloud function?

I'm not sure for your errors. But I'm sure it working fine with NodeJs.
Can you give me more detail about your code snippet? That would be easy for me to check it.

**Comment by oidele** [comment]
**The original error message was resolved when I carried out the below steps but now, I get a new error message. Let me outline all the steps I have carried out below.

Initially when I tried to import the module, I get the "could not find a declaration file for module" error message.
![image](https://user-images.githubusercontent.com/65330604/81936419-ed128d00-95fa-11ea-8690-38027e37d290.png)

To resolve this issue, I created an index.d.ts with a "declare module 'node-geometry-library'" statement 
![image](https://user-images.githubusercontent.com/65330604/81937146-e6d0e080-95fb-11ea-8906-4211718fa618.png)

and added the typeRoots to the tsconfig.json file
![image](https://user-images.githubusercontent.com/65330604/81937327-2b5c7c00-95fc-11ea-963e-47a80cedae26.png)

After doing these steps, the error disappeared and I am able to compile the code.
To do a test, I copied the PolyUtil.encode examples in the usage page and I exported this to firebase cloud
![image](https://user-images.githubusercontent.com/65330604/81937729-ad4ca500-95fc-11ea-8a36-367cf32b4e96.png)

Now, I get another error message when the function is executed from the firebase cloud.
this is the error message from the firebase console output

![image](https://user-images.githubusercontent.com/65330604/81938426-90fd3800-95fd-11ea-8887-8a5824824636.png)

**Comment by BunHouth** [comment]
@oidele thanks you for your screenshot. I'll update package to support typescript soon and example with node js soon.

**Comment by BunHouth** [comment]
@oidele  I have updated my package to support typescript.

For your issue is related with your code. Please check using here [Usage](https://github.com/BunHouth/geometry-library#usage)

Base on your screenshot please change as below:
`import PolyUtil from "node-geometry-library"`
TO
`import {PolyUtil} from "node-geometry-library"`

**Comment by oidele** [comment]
Thanks @BunHouth... I will update my code and check

**Comment by oidele** [comment]
Hi @BunHouth, thanks for your help so far.  I tried executing my code but I got the below error msg 

![image](https://user-images.githubusercontent.com/65330604/82059575-e35a5980-96ce-11ea-9369-58a97f1fdfb0.png)

I think this is because NodeJS uses the CommonJS Module syntax (module.exports) and not the ES6 Module syntax.

**Comment by BunHouth** [comment]
@oidele  for using es6 with node js, you need to use babel. 
please check link below https://qiita.com/suketa/items/91f6ed4a4ea972e004f1

**Comment by BunHouth** [comment]
@oidele  thanks for your feedback. I have publish new version for support CommonJS module export.

**Comment by oidele** [comment]
Awesome...thanks so much @BunHouth. It worked. Cheers
