### ISSUE TITLE
encode does not seem to work on a fine polyline

### ISSUE THREAD

**Issue by martijnsenden** [BunHouth/geometry-library#3]
I just noticed that the polyline encoding doesn't work for a very fine polyline like this one:

```
const finePolyline = [
	{ lat: 0.000003, lng: 0 },
	{ lat: 0.000008, lng: 0 },
	{ lat: 0.000013, lng: 0 },
	{ lat: 0.000029, lng: 0 },
	{ lat: 0.000045, lng: 0 },
	{ lat: 0.000061, lng: 0 },
	{ lat: 0.000077, lng: 0 },
	{ lat: 0.000093, lng: 0 },
];
```

I get "??????C?C?C?C?C?", instead of '??A???C?C?A?C?A?', which I would expect. The latter is the value I get when I generate the encoded polyline on the [Interactive PolylineEncoder Utility](https://developers.google.com/maps/documentation/utilities/polylineutility) from Google.

Any thoughts on this?

**Comment by BunHouth** [comment]
@martijnsenden  Base on your information, here what I'm got during testing:

```
const {PolyUtil} = require('node-geometry-library')

const finePolyline = [
	{ lat: 0.000003, lng: 0 },
	{ lat: 0.000008, lng: 0 },
	{ lat: 0.000013, lng: 0 },
	{ lat: 0.000029, lng: 0 },
	{ lat: 0.000045, lng: 0 },
	{ lat: 0.000061, lng: 0 },
	{ lat: 0.000077, lng: 0 },
	{ lat: 0.000093, lng: 0 },
];

const example7 = PolyUtil.encode(finePolyline);

console.log(`Example = ${example7}`); 
```
Here is the result `Example = ??A???C?C?A?C?A?`

Please let me know if my usage difference from your.

**Comment by BunHouth** [comment]
I have release another version for improve Polyline Encode and Decode

**Comment by martijnsenden** [comment]
Hi there, Sorry for the trouble. I had copied over the code for encoding to my own codebase and cleaned up the formatting to match my own preferences. I accidentally moved the multiplication by 1e5 and rounding to after the point where the deltas are calculated. This works for the course polylines, but the fine one failed. My bad. Thanks for looking into it though! I see you changed quite a bit in the code in that last commit. Are they mainly there for performance reasons or code quality improvement? Or was the previous algorithm outputting bad results in some (edge) cases?

**Comment by martijnsenden** [comment]
Also, you use `coordinate >>= 5;`. I was wondering if this `5` should not be the `factor` value. Or is it always going to be blocks of 5 bits, regardless of the precision? I guess the latter, seeing that they also do it here: https://github.com/hicsail/polyline/blob/master/polyline/codec.py 🤔

**Comment by BunHouth** [comment]
Actually I  have update polyline encode base on [mapbox polyline](https://github.com/mapbox/polyline/blob/master/src/polyline.js#L103)

For precision default value is 5. you also able to override default value.[PolyUtil.ts](https://github.com/BunHouth/geometry-library/blob/master/src/PolyUtil.ts#L494)

**Comment by martijnsenden** [comment]
Yes, I understand I can override the precision, but I was wondering about the line `coordinate >>= 5`. This `5` is unrelated to the precision, am I right? Otherwise, I would expect `coordinate >>= factor`. But like I said, the code is probably correct as it is.

**Comment by martijnsenden** [comment]
And is the MapBox encoding algorithm compatible with the Google encoding algorithm?

**Comment by BunHouth** [comment]
> And is the MapBox encoding algorithm compatible with the Google encoding algorithm?

Yep, it is. I also don't found any issue since I use MapBox encoding.

**Comment by martijnsenden** [comment]
Thanks, good to know

Op wo 10 jun. 2020 12:06 schreef Bunhouth <notifications@github.com>:

**Comment by BunHouth** [comment]
> Yes, I understand I can override the precision, but I was wondering about the line `coordinate >>= 5`. This `5` is unrelated to the precision, am I right? Otherwise, I would expect `coordinate >>= factor`. But like I said, the code is probably correct as it is.

- 5 it not about factor

You can see here https://github.com/klaxit/fast-polylines/blob/master/ext/fast_polylines/fast_polylines.c#L58

that is ruby library Implementation of the  Google polyline algorithm. It the same as MapBox Polyline

**Comment by martijnsenden** [comment]
Yes, I also saw that the python implementation is the same, see link I
provided earlier. Thanks for confirming.

Op wo 10 jun. 2020 12:26 schreef Bunhouth <notifications@github.com>:

**Comment by BunHouth** [comment]
Reference:  https://www.twistedape.me.uk/2014/04/20/google-polyline-encoding/

**Comment by martijnsenden** [comment]
Thanks!

Op wo 10 jun. 2020 12:36 schreef Bunhouth <notifications@github.com>:
