### ISSUE TITLE
PolyUtil.containsLocation Always returning false 

### ISSUE THREAD

**Issue by saikiranvadlakonda** [BunHouth/geometry-library#7]
Hi,

When I'm executing below code on node, it's returning false, but when I try with google's library on UI, it's working as expected. Could you please let me know how to use this on node or correct me where I'm going wrong.

```
var geometry = require('node-geometry-library')
var result = geometry.PolyUtil.containsLocation({lat: -26.8259219, lng:30.4879818},
[{"lat": -26.813981,"lng": 30.442661},{"lat": -26.811871,"lng": 30.445423},{"lat": -26.810641,"lng": 30.446562},{"lat": -26.809322,"lng": 30.447556},{"lat": -26.807405,"lng": 30.44847},{"lat": -26.805377,"lng": 30.449192},{"lat": -26.808737,"lng": 30.465581},{"lat": -26.815032,"lng": 30.483183},{"lat": -26.828493,"lng": 30.513709},{"lat": -26.830484,"lng": 30.511306},{"lat": -26.83148,"lng": 30.51026},{"lat": -26.832841,"lng": 30.509113},{"lat": -26.834992,"lng": 30.507861},{"lat": -26.837317,"lng": 30.506753}] )

console.log(result);
```

The point lies inside the geofence (polygon), could you please let us know where we are going wrong.
Thanks.

**Comment by BunHouth** [comment]
> Hi,
> 
> When I'm executing below code on node, it's returning false, but when I try with google's library on UI, it's working as expected. Could you please let me know how to use this on node or correct me where I'm going wrong.
> 
> ```
> var geometry = require('node-geometry-library')
> var result = geometry.PolyUtil.containsLocation({lat: -26.8259219, lng:30.4879818},
> [{"lat": -26.813981,"lng": 30.442661},{"lat": -26.811871,"lng": 30.445423},{"lat": -26.810641,"lng": 30.446562},{"lat": -26.809322,"lng": 30.447556},{"lat": -26.807405,"lng": 30.44847},{"lat": -26.805377,"lng": 30.449192},{"lat": -26.808737,"lng": 30.465581},{"lat": -26.815032,"lng": 30.483183},{"lat": -26.828493,"lng": 30.513709},{"lat": -26.830484,"lng": 30.511306},{"lat": -26.83148,"lng": 30.51026},{"lat": -26.832841,"lng": 30.509113},{"lat": -26.834992,"lng": 30.507861},{"lat": -26.837317,"lng": 30.506753}] )
> 
> console.log(result);
> ```
> 
> The point lies inside the geofence (polygon), could you please let us know where we are going wrong.
> Thanks.

That bug is fixed. You can update package to latest version.

**Comment by SudaNix** [comment]
The issue exist on last version 1.2.4
sample code return false 

const response =  geometry.PolyUtil.containsLocation(
            {'lat': 38.5, 'lng': -120.2},
            [
                {'lat': 38.5, 'lng': -120.2}, {'lat': 40.7, 'lng': -120.95 }, {'lat': 43.252, 'lng': -126.453}
            ]);

 console.log(`response: ${response}`)

**Comment by BunHouth** [comment]
> The issue exist on last version 1.2.4
> sample code return false
> 
> const response = geometry.PolyUtil.containsLocation(
> {'lat': 38.5, 'lng': -120.2},
> [
> {'lat': 38.5, 'lng': -120.2}, {'lat': 40.7, 'lng': -120.95 }, {'lat': 43.252, 'lng': -126.453}
> ]);
> 
> console.log(`response: ${response}`)

@SudaNix please update to latest version.
